### PR TITLE
Added Vietnamese Input

### PR DESCRIPTION
**Pull request by mybabysexy**
Added Vietnamese Input

Override (Star) button for Vietnamese Special Characters.
e.g.:
- (a) + (*) = (á)

### CODE REVIEW

**Comment by AshiVered** [comment]
Hello, thank on your contribute.
Do your abbreviation changes affect other languages?

**Comment by mybabysexy** [comment]
> Hello, thank on your contribute. Do your abbreviation changes affect other languages?

no, other languages should work as is

**Comment by AshiVered** [comment]
Hey friend,
I'm sorry for the delay, I'm very busy.
As you probably see, I released version 7, with Vietnamese, and another significant change.
Could you translate the interface (strings.xml) and the help file into Vietnamese?
Thank you!

**Comment by mybabysexy** [comment]
Sure, opened a new PR, pls check

**Pull request merged**
